### ISSUE TITLE
The addon repeat itself

### ISSUE THREAD

**Issue by Altarus94** [mwiemarc/wowclassic_tradeskillwhisperlookup#2]
Like the screen show, the addon post multiple time the same item at the first command, and then repost when the guy whisper me again

![image](https://user-images.githubusercontent.com/39195083/67755092-d24e4180-fa37-11e9-82f1-ff403c5f28f9.png)

![image](https://user-images.githubusercontent.com/39195083/67755114-daa67c80-fa37-11e9-906a-0c7bbde671ef.png)

![image](https://user-images.githubusercontent.com/39195083/67755148-eabe5c00-fa37-11e9-8ff8-290350cf37a0.png)

My featured : 
Thorium Shield Spike;Dark Iron Plate;Dark Iron Mail;Arcanite Rod;Mithril Spurs;

**Comment by mwiemarc** [comment]
### **I've released an update _(v0.2.6-beta)_ for that repeating tradeskills/items bug**
#### *(please tell me if this solves your issue)*

#
Your second issue isn't one, it was not reposting after the guy whispered you again, the response was simply not completely sent then. _(the response was also longer than it should be because of that repeating bug)_

**If a response exceeds ~10 messages the first few messages will be sent immediately and the rest is sent in an second interation *(usually a few seconds later or even faster)* to prevent disconnects or stuff like that since there is a limit of allowed data sent by clients in a period of time. 
*(that's was the "Response hint: Response delay" message want's to tell)***

_(This can also result in that a player has to wait a while to get a response if another player also sent a request immediately before)_

#
**_Thanks for your issue submission._**
